# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'labasort.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import random


class Ui_MainWindow(object):
    def __init__(self):
        self.massiv = []
        self.result = []
        self.masiv_res = False
        self.masiv_gen = False

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(550, 290)  # Размеры окна
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Info = QtWidgets.QLabel(self.centralwidget)
        self.Info.setGeometry(QtCore.QRect(10, 0, 550, 61))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Info.setFont(font)
        self.Info.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.Info.setObjectName("Info")
        self.gen_massiv = QtWidgets.QLabel(self.centralwidget)
        self.gen_massiv.setGeometry(QtCore.QRect(100, 60, 450, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.gen_massiv.setFont(font)
        self.gen_massiv.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.gen_massiv.setText("")
        self.gen_massiv.setObjectName("gen_massiv")
        self.info_massiv = QtWidgets.QLabel(self.centralwidget)
        self.info_massiv.setGeometry(QtCore.QRect(10, 60, 91, 61))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.info_massiv.setFont(font)
        self.info_massiv.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.info_massiv.setObjectName("info_massiv")
        self.Info_sort = QtWidgets.QLabel(self.centralwidget)
        self.Info_sort.setGeometry(QtCore.QRect(10, 120, 91, 61))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Info_sort.setFont(font)
        self.Info_sort.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.Info_sort.setObjectName("Info_sort")
        self.gen_sort_massiv = QtWidgets.QLabel(self.centralwidget)
        self.gen_sort_massiv.setGeometry(QtCore.QRect(100, 120, 450, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.gen_sort_massiv.setFont(font)
        self.gen_sort_massiv.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.gen_sort_massiv.setText("")
        self.gen_sort_massiv.setObjectName("gen_sort_massiv")
        self.btn_gen_massiv = QtWidgets.QPushButton(self.centralwidget)
        self.btn_gen_massiv.setGeometry(QtCore.QRect(100, 180, 361, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_gen_massiv.setFont(font)
        self.btn_gen_massiv.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.btn_gen_massiv.setObjectName("btn_gen_massiv")
        self.btn_sort_massiv = QtWidgets.QPushButton(self.centralwidget)
        self.btn_sort_massiv.setGeometry(QtCore.QRect(100, 240, 361, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_sort_massiv.setFont(font)
        self.btn_sort_massiv.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.btn_sort_massiv.setObjectName("btn_sort_massiv")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.add_functions()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Info.setText(_translate("MainWindow", " Отсортировать массив по возрастанию суммы цифр"))
        self.info_massiv.setText(_translate("MainWindow", "Массив"))
        self.Info_sort.setText(_translate("MainWindow", "Сортировака"))
        self.btn_gen_massiv.setText(_translate("MainWindow", "Сгенерировать массив"))
        self.btn_sort_massiv.setText(_translate("MainWindow", "Отсортировать массив"))

    def add_functions(self):
        self.btn_gen_massiv.clicked.connect(self.write_masiv)
        self.btn_sort_massiv.clicked.connect(self.sort_masiver)

    """Создание массива"""

    def gen_masiv(self):
        N = 10
        for i in range(N):
            numbers = random.randint(1, 600)
            self.massiv.append(numbers)

    """Запись массива в блок"""

    def write_masiv(self):
        self.gen_masiv()
        if self.masiv_res == False:
            self.gen_massiv.setText(str(self.massiv))
            self.masiv_res = True
        elif self.masiv_res == True:
            self.massiv = []
            self.gen_massiv.setText(str(self.massiv))
            self.masiv_res = False


    """Сортировка масива"""

    def sort_masiver(self):
        self.result = sorted(self.massiv, key=lambda x: (sum(map(int, str(x)))))
        if self.masiv_gen == False:
            self.gen_sort_massiv.setText(str(self.result))
            self.masiv_gen = True
        elif self.masiv_gen == True:
            self.result = []
            self.gen_sort_massiv.setText(str(self.result))
            self.masiv_gen = False





if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
